"""Nexus — Streamlit setup & profile UI.

Launch: streamlit run ui/streamlit_app.py
"""

from __future__ import annotations

import io
import json
import re
from itertools import groupby
from pathlib import Path

import streamlit as st
import yaml

ROOT = Path(__file__).parent.parent

AGENT_CONFIG    = ROOT / "resources" / "config" / "agent_config.yaml"
CAREER_PATHS_FILE = ROOT / "resources" / "config" / "career_paths.yaml"
SKILLS_FILE     = ROOT / "resources" / "skills" / "skills_profile.yaml"
RESUME_A        = ROOT / "resources" / "resumes" / "resume_path_a.md"
RESUME_B        = ROOT / "resources" / "resumes" / "resume_path_b.md"
ENV_FILE        = ROOT / ".env"


# ── I/O helpers ────────────────────────────────────────────────────────────────

def _read_yaml(path: Path) -> dict:
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    return {}


def _write_yaml(path: Path, data: dict, header: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        if header:
            f.write(header + "\n\n")
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def _read_env() -> dict:
    env: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def _write_env(env: dict) -> None:
    SECTIONS = [
        ("Job Platforms",    ["NAUKRI_EMAIL", "NAUKRI_PASSWORD"]),
        ("Notifications",    ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID",
                               "GMAIL_SENDER", "GMAIL_RECIPIENT",
                               "GMAIL_CREDENTIALS_PATH", "GMAIL_TOKEN_PATH"]),
        ("Candidate Details",["CANDIDATE_NAME", "CANDIDATE_EMAIL", "CANDIDATE_PHONE"]),
        ("Scheduling",       ["TIMEZONE", "APPLY_DEADLINE_IST"]),
        ("Database",         ["DATABASE_URL"]),
        ("Logging",          ["LOG_LEVEL", "LOG_FILE"]),
    ]
    lines = ["# ─── Nexus — generated by Nexus UI ──────────────────────────────────────────", ""]
    for section, keys in SECTIONS:
        pad = "─" * max(1, 58 - len(section))
        lines.append(f"# ─── {section} {pad}─")
        for k in keys:
            lines.append(f"{k}={env.get(k, '')}")
        lines.append("")
    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")


def _lines(s: str) -> list[str]:
    return [l.strip() for l in s.splitlines() if l.strip()]


# ── Resume parsing ─────────────────────────────────────────────────────────────

def _extract_resume_text(uploaded_file) -> str:
    name = uploaded_file.name.lower()
    raw  = uploaded_file.read()

    if name.endswith(".pdf"):
        try:
            import pdfplumber
            parts: list[str] = []
            with pdfplumber.open(io.BytesIO(raw)) as pdf:
                for page in pdf.pages:
                    text = page.extract_text()
                    if text:
                        parts.append(text)
            return "\n".join(parts)
        except Exception as exc:
            st.warning(f"PDF parse error: {exc}. Try DOCX or Markdown.")
            return ""

    if name.endswith(".docx"):
        try:
            import docx
            doc = docx.Document(io.BytesIO(raw))
            return "\n".join(p.text for p in doc.paragraphs if p.text.strip())
        except Exception as exc:
            st.warning(f"DOCX parse error: {exc}.")
            return ""

    if name.endswith((".md", ".txt")):
        return raw.decode("utf-8", errors="ignore")

    st.warning("Unsupported file type — upload PDF, DOCX, or Markdown.")
    return ""


_EXTRACTION_PROMPT = """\
Extract structured information from this resume. Return ONLY a valid JSON object — \
no prose, no markdown fences. Rate each skill 1–10 based on evidence: \
9–10 = clear strength, 7–8 = mentioned with context, 5–6 = briefly mentioned, 1–4 = not found.

{{
  "name": "full name",
  "email": "email or empty string",
  "phone": "phone with country code or empty string",
  "title": "most recent job title",
  "location": "city, country",
  "experience_years": <integer>,
  "summary": "2–3 sentence professional summary drawn from the resume",
  "preferred_locations": ["city", "Remote"],

  "career": {{
    "path_b_titles": ["3-5 target job titles the candidate should auto-apply for, based on their current seniority"],
    "path_a_titles": ["2-3 stretch/senior titles one level above their current role"],
    "search_keywords": ["6-10 job search keywords derived from their strongest skills and target roles"],
    "strong_positives": ["4-6 technical/leadership keywords from their resume that strongly signal fit"],
    "mild_positives": ["4-6 supporting keywords that are relevant but not their core strength"],
    "strong_negatives": ["terms like fresher, junior, 0-2 years that would disqualify them"],
    "mild_negatives": ["domains they have no experience in, e.g. gaming, hardware, embedded"]
  }},

  "skills": {{
    "leadership":    {{"team_building":7,"strategy":7,"stakeholder_management":7,"cross_functional":7,"agile_scrum":7}},
    "qa_engineering":{{"test_automation":7,"api_testing":7,"ui_automation":7,"performance_testing":6,"shift_left":7}},
    "cicd_devops":   {{"cicd_pipeline":7,"github_actions":7,"docker":6,"aws":5}},
    "tools":         {{"selenium":7,"pytest":7,"jira":7,"postman":7}},
    "languages":     {{"python":7,"java":6,"sql":7}},
    "soft_skills":   {{"communication":8,"mentoring":8}}
  }}
}}

Resume text:
{text}
"""


def _parse_with_ollama(text: str) -> dict:
    try:
        import ollama
        response = ollama.chat(
            model="llama3.2",
            messages=[{"role": "user", "content": _EXTRACTION_PROMPT.format(text=text[:8000])}],
            options={"temperature": 0.1},
        )
        raw   = response["message"]["content"]
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            return json.loads(match.group())
    except Exception:
        pass
    return {}


def _parse_with_regex(text: str) -> dict:
    result: dict = {}
    if m := re.search(r"[\w.+\-]+@[\w\-]+\.[a-zA-Z]{2,}", text):
        result["email"] = m.group()
    if m := re.search(r"(\+\d[\d\s\-]{8,15})", text):
        result["phone"] = m.group().strip()
    if m := re.search(r"(\d{1,2})[\s\-]year", text, re.IGNORECASE):
        result["experience_years"] = int(m.group(1))
    for line in text.splitlines():
        line = line.strip().lstrip("#").strip()
        if line and not re.search(r"[@|/\\]", line) and 1 < len(line.split()) <= 6:
            result["name"] = line
            break
    return result


def _parse_resume(uploaded_file) -> dict:
    text = _extract_resume_text(uploaded_file)
    if not text:
        return {}
    with st.spinner("Parsing resume with Ollama…"):
        parsed = _parse_with_ollama(text)
    if not parsed:
        st.info("Ollama unavailable — using basic extraction. Skills will use defaults.")
        parsed = _parse_with_regex(text)
    return parsed


# ── Skill catalogue ────────────────────────────────────────────────────────────

# (category_key, skill_key, display_label, keywords)
_SKILLS: list[tuple[str, str, str, list[str]]] = [
    ("leadership",    "team_building",         "Team Building",                   ["team building", "hiring", "QA org"]),
    ("leadership",    "strategy",              "Quality Strategy",                ["quality strategy", "test strategy", "QA roadmap"]),
    ("leadership",    "stakeholder_management","Stakeholder Management",           ["stakeholder", "executive reporting", "OKR"]),
    ("leadership",    "cross_functional",      "Cross-Functional Collaboration",   ["cross-functional", "PM alignment"]),
    ("leadership",    "agile_scrum",           "Agile / Scrum",                   ["agile", "scrum", "sprint", "kanban"]),
    ("qa_engineering","test_automation",       "Test Automation Architecture",     ["automation architecture", "test framework"]),
    ("qa_engineering","api_testing",           "API Testing",                     ["API testing", "REST", "GraphQL", "Postman"]),
    ("qa_engineering","ui_automation",         "UI Automation",                   ["UI automation", "Selenium", "Playwright"]),
    ("qa_engineering","performance_testing",   "Performance Testing",              ["performance testing", "JMeter", "k6"]),
    ("qa_engineering","shift_left",            "Shift-Left / TDD / BDD",          ["shift-left", "TDD", "BDD"]),
    ("cicd_devops",   "cicd_pipeline",         "CI/CD Pipeline Design",            ["CI/CD", "continuous integration"]),
    ("cicd_devops",   "github_actions",        "GitHub Actions",                  ["GitHub Actions"]),
    ("cicd_devops",   "docker",                "Docker",                          ["Docker", "containerization"]),
    ("cicd_devops",   "aws",                   "AWS / Cloud",                     ["AWS", "cloud"]),
    ("tools",         "selenium",              "Selenium",                        ["Selenium", "WebDriver"]),
    ("tools",         "pytest",               "pytest",                          ["pytest", "Python testing"]),
    ("tools",         "jira",                 "Jira",                            ["Jira", "issue tracking"]),
    ("tools",         "postman",              "Postman",                         ["Postman", "API client"]),
    ("languages",     "python",               "Python",                          ["Python", "scripting"]),
    ("languages",     "java",                 "Java",                            ["Java", "Maven"]),
    ("languages",     "sql",                  "SQL",                             ["SQL", "database testing"]),
    ("soft_skills",   "communication",        "Communication & Presentation",     ["communication", "presentation"]),
    ("soft_skills",   "mentoring",            "Mentoring / Coaching",            ["mentoring", "coaching"]),
]

_CAT_LABELS: dict[str, str] = {
    "leadership":    "Leadership & Strategy",
    "qa_engineering":"QA Engineering",
    "cicd_devops":   "CI/CD & DevOps",
    "tools":         "Tools",
    "languages":     "Programming Languages",
    "soft_skills":   "Soft Skills",
}

def _sk(cat: str, skill: str) -> str:
    """Session-state key for a skill rating."""
    return f"wz_s_{cat}_{skill}"


# ── Wizard state ───────────────────────────────────────────────────────────────

def _init_wizard_state() -> None:
    """Seed session_state from YAML/env once per session. No-op on reruns."""
    if st.session_state.get("_wz_init"):
        return

    cfg     = _read_yaml(AGENT_CONFIG)
    skills  = _read_yaml(SKILLS_FILE)
    cp      = _read_yaml(CAREER_PATHS_FILE)
    env     = _read_env()

    profile  = skills.get("profile", {})
    prefs    = skills.get("preferences", {})
    sched    = cfg.get("schedule", {})
    sys_cfg  = cfg.get("system", {})
    scout    = cfg.get("scout", {})
    pa       = cp.get("paths", {}).get("path_a", {})
    pb       = cp.get("paths", {}).get("path_b", {})
    signals  = cp.get("scoring_signals", {})

    sd = st.session_state.setdefault  # shorthand

    # Step 1 — Profile & Schedule
    sd("wz_name",         profile.get("name", ""))
    sd("wz_email",        env.get("CANDIDATE_EMAIL", profile.get("email", "")))
    sd("wz_phone",        env.get("CANDIDATE_PHONE", ""))
    sd("wz_title",        profile.get("title", "Senior QE Manager"))
    sd("wz_location",     profile.get("location", "Hyderabad, India"))
    sd("wz_exp",          int(profile.get("experience_years", 10)))
    sd("wz_locs",         ", ".join(prefs.get("preferred_locations", ["Hyderabad", "Remote"])))
    sd("wz_summary",      skills.get("summary", ""))
    sd("wz_remote_ok",    prefs.get("remote_ok", True))
    sd("wz_relocation_ok",prefs.get("relocation_ok", False))
    sd("wz_notice",       int(prefs.get("notice_period_days", 30)))
    sd("wz_timezone",     sys_cfg.get("timezone", "Asia/Kolkata"))
    sd("wz_scout_start",  sched.get("scout_start", "05:00"))
    sd("wz_deadline",     sched.get("apply_deadline", "09:15"))

    # Step 2 — Career Paths
    sd("wz_pb_titles",    "\n".join(pb.get("target_titles", ["Senior QE Manager", "QA Manager", "Lead QE"])))
    sd("wz_pb_threshold", int(pb.get("score_threshold", 72)))
    sd("wz_pb_max",       int(pb.get("max_per_day", 15)))
    sd("wz_pa_titles",    "\n".join(pa.get("target_titles", ["Director of QA", "Head of Quality"])))
    sd("wz_pa_threshold", int(pa.get("score_threshold", 60)))
    sd("wz_pa_max",       int(pa.get("max_per_day", 3)))
    sd("wz_keywords",     "\n".join(scout.get("keywords", [])))
    sd("wz_locations",    "\n".join(scout.get("locations", ["Hyderabad", "Remote"])))
    sd("wz_exclude",      "\n".join(scout.get("exclude_keywords", ["fresher", "junior"])))
    sd("wz_sig_sp",       "\n".join(signals.get("strong_positive", [])))
    sd("wz_sig_mp",       "\n".join(signals.get("mild_positive", [])))
    sd("wz_sig_sn",       "\n".join(signals.get("strong_negative", [])))
    sd("wz_sig_mn",       "\n".join(signals.get("mild_negative", [])))

    # Step 3 — Skills
    for cat_key, skill_key, _, _ in _SKILLS:
        cat_data   = skills.get(cat_key, {})
        skill_data = cat_data.get(skill_key, {})
        rating     = int(skill_data.get("rating", 5)) if isinstance(skill_data, dict) else 5
        sd(_sk(cat_key, skill_key), rating)

    st.session_state["_wz_init"] = True


def _apply_resume_to_state(parsed: dict) -> None:
    """Overwrite wizard session_state with resume-parsed data (all steps)."""
    # Step 1 — Profile
    mapping = {
        "name": "wz_name", "email": "wz_email", "phone": "wz_phone",
        "title": "wz_title", "location": "wz_location", "summary": "wz_summary",
    }
    for src, dst in mapping.items():
        if parsed.get(src):
            st.session_state[dst] = parsed[src]
    if parsed.get("experience_years"):
        st.session_state["wz_exp"] = int(parsed["experience_years"])
    if parsed.get("preferred_locations"):
        st.session_state["wz_locs"] = ", ".join(parsed["preferred_locations"])

    # Step 2 — Career Paths (LLM-extracted)
    career = parsed.get("career", {})
    if career.get("path_b_titles"):
        st.session_state["wz_pb_titles"] = "\n".join(career["path_b_titles"])
    if career.get("path_a_titles"):
        st.session_state["wz_pa_titles"] = "\n".join(career["path_a_titles"])
    if career.get("search_keywords"):
        st.session_state["wz_keywords"] = "\n".join(career["search_keywords"])
    if career.get("strong_positives"):
        st.session_state["wz_sig_sp"] = "\n".join(career["strong_positives"])
    if career.get("mild_positives"):
        st.session_state["wz_sig_mp"] = "\n".join(career["mild_positives"])
    if career.get("strong_negatives"):
        st.session_state["wz_sig_sn"] = "\n".join(career["strong_negatives"])
    if career.get("mild_negatives"):
        st.session_state["wz_sig_mn"] = "\n".join(career["mild_negatives"])

    # Step 3 — Skills
    for cat_key, skill_key, _, _ in _SKILLS:
        rating = parsed.get("skills", {}).get(cat_key, {}).get(skill_key)
        if rating is not None:
            st.session_state[_sk(cat_key, skill_key)] = int(rating)


# ── Save helpers ───────────────────────────────────────────────────────────────

def _save_profile() -> None:
    skills = _read_yaml(SKILLS_FILE)
    cfg    = _read_yaml(AGENT_CONFIG)
    env    = _read_env()

    pref_locs = [l.strip() for l in st.session_state["wz_locs"].split(",") if l.strip()]
    skills["profile"] = {
        "name":             st.session_state["wz_name"],
        "title":            st.session_state["wz_title"],
        "location":         st.session_state["wz_location"],
        "experience_years": st.session_state["wz_exp"],
        "email":            st.session_state["wz_email"],
    }
    skills["summary"]     = st.session_state["wz_summary"]
    skills["preferences"] = {
        "preferred_locations": pref_locs,
        "remote_ok":           st.session_state["wz_remote_ok"],
        "relocation_ok":       st.session_state["wz_relocation_ok"],
        "notice_period_days":  st.session_state["wz_notice"],
    }
    _write_yaml(SKILLS_FILE, skills,
        "# ─── Nexus Skills Profile ────────────────────────────────────────────────────\n"
        "# Rate each skill 1–10. The Scorer uses these weights against job requirements.")

    cfg.setdefault("system", {})["timezone"] = st.session_state["wz_timezone"]
    cfg.setdefault("schedule", {}).update({
        "scout_start":    st.session_state["wz_scout_start"],
        "apply_deadline": st.session_state["wz_deadline"],
    })
    cfg.setdefault("apply", {})["candidate_experience_years"] = st.session_state["wz_exp"]
    _write_yaml(AGENT_CONFIG, cfg, "# ─── Nexus Agent Configuration ──────────────────────────────────────────────")

    env.update({
        "CANDIDATE_NAME":  st.session_state["wz_name"],
        "CANDIDATE_EMAIL": st.session_state["wz_email"],
        "CANDIDATE_PHONE": st.session_state["wz_phone"],
        "TIMEZONE":        st.session_state["wz_timezone"],
        "APPLY_DEADLINE_IST": st.session_state["wz_deadline"],
    })
    env.setdefault("DATABASE_URL", "sqlite:///db/nexus.db")
    env.setdefault("LOG_LEVEL", "INFO")
    env.setdefault("LOG_FILE", "logs/nexus.log")
    _write_env(env)


def _save_career() -> None:
    cfg = _read_yaml(AGENT_CONFIG)

    cp_data = {
        "paths": {
            "path_a": {
                "name": "Stretch / Senior Track",
                "description": "Roles requiring personal judgment — Nexus queues these for your review",
                "human_approval_required": True,
                "max_per_day":     st.session_state["wz_pa_max"],
                "score_threshold": st.session_state["wz_pa_threshold"],
                "resume_variant":  "path_a",
                "auto_apply":      False,
                "queue_label":     "Needs Your Review",
                "target_titles":   _lines(st.session_state["wz_pa_titles"]),
            },
            "path_b": {
                "name": "Primary Track",
                "description": "Strong-fit roles — Nexus applies automatically before the deadline",
                "human_approval_required": False,
                "max_per_day":     st.session_state["wz_pb_max"],
                "score_threshold": st.session_state["wz_pb_threshold"],
                "resume_variant":  "path_b",
                "auto_apply":      True,
                "queue_label":     "Auto-Applied",
                "target_titles":   _lines(st.session_state["wz_pb_titles"]),
            },
        },
        "scoring_signals": {
            "strong_positive": _lines(st.session_state["wz_sig_sp"]),
            "mild_positive":   _lines(st.session_state["wz_sig_mp"]),
            "strong_negative": _lines(st.session_state["wz_sig_sn"]),
            "mild_negative":   _lines(st.session_state["wz_sig_mn"]),
        },
    }
    _write_yaml(CAREER_PATHS_FILE, cp_data,
        "# ─── Nexus Career Paths ─────────────────────────────────────────────────────")

    cfg.setdefault("scout", {}).update({
        "keywords":        _lines(st.session_state["wz_keywords"]),
        "locations":       _lines(st.session_state["wz_locations"]),
        "exclude_keywords":_lines(st.session_state["wz_exclude"]),
    })
    cfg.setdefault("scorer", {}).update({
        "path_b_threshold": st.session_state["wz_pb_threshold"],
        "path_a_threshold": st.session_state["wz_pa_threshold"],
    })
    _write_yaml(AGENT_CONFIG, cfg, "# ─── Nexus Agent Configuration ──────────────────────────────────────────────")


def _save_skills() -> None:
    skills = _read_yaml(SKILLS_FILE)
    cats: dict = {}
    for cat_key, skill_key, _, kws in _SKILLS:
        cats.setdefault(cat_key, {})[skill_key] = {
            "rating":   st.session_state.get(_sk(cat_key, skill_key), 5),
            "keywords": kws,
        }
    for cat_key, data in cats.items():
        skills[cat_key] = data
    _write_yaml(SKILLS_FILE, skills,
        "# ─── Nexus Skills Profile ────────────────────────────────────────────────────\n"
        "# Rate each skill 1–10. The Scorer uses these weights against job requirements.")


def _save_wizard_step(step: int) -> None:
    if step == 0:
        _save_profile()
    elif step == 1:
        _save_career()
    elif step == 2:
        _save_skills()
    # step 3 (resumes) saves via its own inline buttons


# ── Wizard UI ──────────────────────────────────────────────────────────────────

def _step_indicator(current: int, labels: list[str]) -> None:
    cols = st.columns(len(labels))
    for i, (col, label) in enumerate(zip(cols, labels)):
        with col:
            if i < current:
                st.markdown(
                    f"<div style='text-align:center;color:#10b981;font-size:0.82rem'>✅ {label}</div>",
                    unsafe_allow_html=True)
            elif i == current:
                st.markdown(
                    f"<div style='text-align:center;color:#6366f1;font-weight:700;font-size:0.88rem'>● {label}</div>",
                    unsafe_allow_html=True)
            else:
                st.markdown(
                    f"<div style='text-align:center;color:#9ca3af;font-size:0.82rem'>○ {label}</div>",
                    unsafe_allow_html=True)
    st.progress(current / max(len(labels) - 1, 1))


# ── Step 1: Profile & Schedule ─────────────────────────────────────────────────

def _step_profile() -> None:
    # Resume upload — Ria's extract flow pre-fills all steps
    with st.expander(
        "⬆️  Upload resume to auto-fill all steps",
        expanded=not bool(st.session_state.get("wz_name")),
    ):
        st.caption(
            "PDF, DOCX, or Markdown. Ria extracts your profile, skills, and career keywords "
            "and pre-fills every step at once — just review and continue."
        )
        uploaded = st.file_uploader(
            "resume", type=["pdf", "docx", "md", "txt"],
            label_visibility="collapsed", key="wz_upload",
        )
        if uploaded and st.session_state.get("_wz_last_upload") != uploaded.name:
            parsed = _parse_resume(uploaded)
            if parsed:
                st.session_state["_wz_last_upload"] = uploaded.name
                _apply_resume_to_state(parsed)
                hits = [k for k in ("name","email","phone","title","location","experience_years") if parsed.get(k)]
                n_skills = sum(len(v) for v in parsed.get("skills", {}).values())
                st.success(
                    f"Extracted {len(hits)} profile fields and {n_skills} skill ratings across all steps. "
                    "Review each step before finishing."
                )
                st.rerun()
            else:
                st.error("Could not extract data. Ensure the file contains selectable text.")

    st.subheader("Personal Information")
    c1, c2 = st.columns(2)
    with c1:
        st.text_input("Full Name",                   key="wz_name")
        st.text_input("Email",                       key="wz_email")
        st.text_input("Phone (e.g. +91XXXXXXXXXX)",  key="wz_phone")
    with c2:
        st.text_input("Current Title",               key="wz_title")
        st.text_input("Location",                    key="wz_location")
        st.number_input("Years of QA Experience", min_value=0, max_value=50, step=1, key="wz_exp")

    st.text_input("Preferred Job Locations (comma-separated)", key="wz_locs")

    st.subheader("Professional Summary")
    st.text_area(
        "Summary (fed to scorer — factual, keyword-rich)",
        key="wz_summary", height=120,
    )

    st.subheader("Preferences")
    c1, c2, c3 = st.columns(3)
    with c1: st.checkbox("Remote OK",       key="wz_remote_ok")
    with c2: st.checkbox("Relocation OK",   key="wz_relocation_ok")
    with c3: st.number_input("Notice Period (days)", min_value=0, max_value=180, step=1, key="wz_notice")

    st.subheader("Schedule")
    c1, c2, c3 = st.columns(3)
    with c1: st.text_input("Timezone",               key="wz_timezone")
    with c2: st.text_input("Pipeline Start (HH:MM)", key="wz_scout_start")
    with c3: st.text_input("Apply Deadline (HH:MM)", key="wz_deadline")


# ── Step 2: Career Paths ───────────────────────────────────────────────────────

def _step_career() -> None:
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Path B — Auto-Apply")
        st.caption("Primary track · Nexus submits before the deadline.")
        st.text_area("Titles (one per line)", key="wz_pb_titles", height=130)
        st.slider("Min Score to Auto-Apply", 0, 100, key="wz_pb_threshold")
        st.number_input("Max Applications / Day", min_value=1, max_value=50, step=1, key="wz_pb_max")
    with c2:
        st.subheader("Path A — Human Review")
        st.caption("Stretch roles · Nexus queues, you decide.")
        st.text_area("Titles (one per line)", key="wz_pa_titles", height=130)
        st.slider("Min Score to Queue", 0, 100, key="wz_pa_threshold")
        st.number_input("Max Queued / Day", min_value=1, max_value=20, step=1, key="wz_pa_max")

    st.divider()
    st.subheader("Search Configuration")
    c1, c2 = st.columns(2)
    with c1:
        st.text_area("Search Keywords (one per line)",  key="wz_keywords",  height=120)
        st.text_area("Search Locations (one per line)", key="wz_locations", height=80)
    with c2:
        st.text_area("Exclude Keywords (one per line)", key="wz_exclude",   height=120)

    st.divider()
    st.subheader("Scoring Signals")
    c1, c2 = st.columns(2)
    with c1:
        st.text_area("Strong Positives (+boost)",       key="wz_sig_sp", height=100)
        st.text_area("Mild Positives (+small boost)",   key="wz_sig_mp", height=100)
    with c2:
        st.text_area("Strong Negatives (−disqualify)",  key="wz_sig_sn", height=100)
        st.text_area("Mild Negatives (−penalty)",       key="wz_sig_mn", height=100)


# ── Step 3: Skills ─────────────────────────────────────────────────────────────

def _step_skills() -> None:
    if st.session_state.get("_wz_last_upload"):
        st.info("Skill ratings were pre-filled from your resume. Adjust any before continuing.")
    st.caption("Rate each skill 1–10. The Scorer weights these against job description requirements.")

    for cat_key, group in groupby(_SKILLS, key=lambda x: x[0]):
        st.subheader(_CAT_LABELS[cat_key])
        skill_list = list(group)
        cols = st.columns(2)
        for i, (ck, sk, label, _) in enumerate(skill_list):
            with cols[i % 2]:
                st.slider(label, 1, 10, key=_sk(ck, sk))


# ── Step 4: Resumes ────────────────────────────────────────────────────────────

def _step_resumes() -> None:
    st.caption(
        "Edit your resumes in Markdown. Nexus submits these as-is — "
        "keep them ATS-friendly and keyword-rich."
    )
    tab_b, tab_a = st.tabs(["Path B — Primary Track (auto-applied)", "Path A — Stretch Roles (review queue)"])

    with tab_b:
        st.caption("Used for Senior QE Manager / QA Manager auto-applications.")
        content_b = RESUME_B.read_text(encoding="utf-8") if RESUME_B.exists() else (
            "# Your Name\n\n## Summary\n\n## Experience\n\n## Skills\n"
        )
        ce, cp = st.columns([3, 2])
        with ce:
            new_b = st.text_area("", value=content_b, height=520, key="wz_resume_b", label_visibility="collapsed")
            if st.button("Save Path B Resume", type="primary", key="wz_save_b"):
                RESUME_B.parent.mkdir(parents=True, exist_ok=True)
                RESUME_B.write_text(new_b, encoding="utf-8")
                st.success("Path B resume saved.")
        with cp:
            st.markdown("**Preview**")
            st.markdown(new_b)

    with tab_a:
        st.caption("Used for Director / VP / Head of QE roles — queued for your review.")
        content_a = RESUME_A.read_text(encoding="utf-8") if RESUME_A.exists() else (
            "# Your Name\n\n## Summary\n\n## Experience\n\n## Skills\n"
        )
        ce, cp = st.columns([3, 2])
        with ce:
            new_a = st.text_area("", value=content_a, height=520, key="wz_resume_a", label_visibility="collapsed")
            if st.button("Save Path A Resume", type="primary", key="wz_save_a"):
                RESUME_A.parent.mkdir(parents=True, exist_ok=True)
                RESUME_A.write_text(new_a, encoding="utf-8")
                st.success("Path A resume saved.")
        with cp:
            st.markdown("**Preview**")
            st.markdown(new_a)


# ── Settings wizard orchestrator ───────────────────────────────────────────────

_WIZARD_STEPS = [
    ("👤  Profile & Schedule", _step_profile),
    ("🎯  Career Paths",       _step_career),
    ("⭐  Skills",             _step_skills),
    ("📄  Resumes",            _step_resumes),
]


def page_settings_wizard() -> None:
    _init_wizard_state()
    st.session_state.setdefault("wz_step", 0)

    step   = st.session_state["wz_step"]
    labels = [s[0] for s in _WIZARD_STEPS]

    st.title("Settings")
    _step_indicator(step, labels)
    st.divider()

    _WIZARD_STEPS[step][1]()

    st.divider()
    col_back, col_gap, col_next = st.columns([2, 3, 2])
    with col_back:
        if step > 0 and st.button("← Back", use_container_width=True):
            _save_wizard_step(step)
            st.session_state["wz_step"] -= 1
            st.rerun()
    with col_next:
        if step < len(_WIZARD_STEPS) - 1:
            if st.button("Save & Continue →", type="primary", use_container_width=True):
                _save_wizard_step(step)
                st.session_state["wz_step"] += 1
                st.rerun()
        else:
            if st.button("✅  Finish Setup", type="primary", use_container_width=True):
                _save_wizard_step(step)
                st.success(
                    "All settings saved! "
                    "Run `python orchestrator.py run --dry-run` to test the pipeline."
                )


# ── Other pages ────────────────────────────────────────────────────────────────

def page_dashboard() -> None:
    st.title("Dashboard")

    cfg    = _read_yaml(AGENT_CONFIG)
    skills = _read_yaml(SKILLS_FILE)

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        live = cfg.get("apply", {}).get("live_mode", False)
        st.metric("Live Mode", "ON" if live else "OFF", delta="active" if live else "safe")
    with c2:
        name = skills.get("profile", {}).get("name", "Not configured")
        st.metric("Profile", name[:20] + "…" if len(name) > 20 else name)
    with c3:
        deadline = cfg.get("schedule", {}).get("apply_deadline", "09:15")
        st.metric("Apply Deadline", f"{deadline} IST")
    with c4:
        thresh = cfg.get("scorer", {}).get("path_b_threshold", 72)
        st.metric("Path B Threshold", f"{thresh}/100")

    st.divider()
    cl, cr = st.columns(2)
    with cl:
        st.subheader("Config Files")
        for label, path in {
            "Agent Config":    AGENT_CONFIG,
            "Career Paths":    CAREER_PATHS_FILE,
            "Skills Profile":  SKILLS_FILE,
            "Resume — Path A": RESUME_A,
            "Resume — Path B": RESUME_B,
            ".env":            ENV_FILE,
        }.items():
            icon = "✅" if path.exists() else "❌"
            st.write(f"{icon} `{path.relative_to(ROOT)}`")
    with cr:
        st.subheader("Quick Reference")
        st.code(
            "# Safe test — no real submissions\n"
            "python orchestrator.py run --dry-run\n\n"
            "# Check status\n"
            "python orchestrator.py status\n\n"
            "# Daemon (5–9 AM IST, every 30 min)\n"
            "python orchestrator.py schedule",
            language="bash",
        )

    if CAREER_PATHS_FILE.exists():
        st.divider()
        st.subheader("Active Career Paths")
        cp = _read_yaml(CAREER_PATHS_FILE)
        ca, cb = st.columns(2)
        with ca:
            pa = cp.get("paths", {}).get("path_a", {})
            st.markdown(f"**Path A — {pa.get('name','Stretch')}**")
            st.caption(f"Score ≥ {pa.get('score_threshold',60)} · Max {pa.get('max_per_day',3)}/day · Human review")
            for t in pa.get("target_titles", []):
                st.write(f"  • {t}")
        with cb:
            pb = cp.get("paths", {}).get("path_b", {})
            st.markdown(f"**Path B — {pb.get('name','Primary')}**")
            st.caption(f"Score ≥ {pb.get('score_threshold',72)} · Max {pb.get('max_per_day',15)}/day · Auto-applied")
            for t in pb.get("target_titles", []):
                st.write(f"  • {t}")


def page_notifications() -> None:
    st.title("Notifications & Credentials")
    env = _read_env()

    with st.form("notif_form"):
        st.subheader("Telegram")
        st.caption("Create a bot via @BotFather · Get your Chat ID via @userinfobot")
        c1, c2 = st.columns(2)
        with c1: tg_token = st.text_input("Bot Token", value=env.get("TELEGRAM_BOT_TOKEN",""), type="password")
        with c2: tg_chat  = st.text_input("Chat ID",   value=env.get("TELEGRAM_CHAT_ID",""))

        st.subheader("Gmail")
        c1, c2 = st.columns(2)
        with c1: gmail_sender    = st.text_input("Sender Address",    value=env.get("GMAIL_SENDER",""))
        with c2: gmail_recipient = st.text_input("Recipient Address", value=env.get("GMAIL_RECIPIENT",""))

        st.subheader("Naukri")
        st.caption("Credentials saved to .env — also run `store-creds naukri` for OS keyring.")
        c1, c2 = st.columns(2)
        with c1: naukri_email = st.text_input("Naukri Email",    value=env.get("NAUKRI_EMAIL",""))
        with c2: naukri_pass  = st.text_input("Naukri Password", value="", type="password",
                                               placeholder="Leave blank to keep existing")

        submitted = st.form_submit_button("Save Credentials", type="primary")

    if submitted:
        env["TELEGRAM_BOT_TOKEN"] = tg_token
        env["TELEGRAM_CHAT_ID"]   = tg_chat
        env["GMAIL_SENDER"]       = gmail_sender
        env["GMAIL_RECIPIENT"]    = gmail_recipient
        env.setdefault("GMAIL_CREDENTIALS_PATH", "resources/credentials/gmail_credentials.json")
        env.setdefault("GMAIL_TOKEN_PATH",        "resources/credentials/gmail_token.json")
        env["NAUKRI_EMAIL"] = naukri_email
        if naukri_pass:
            env["NAUKRI_PASSWORD"] = naukri_pass
        env.setdefault("DATABASE_URL", "sqlite:///db/nexus.db")
        env.setdefault("LOG_LEVEL",    "INFO")
        env.setdefault("LOG_FILE",     "logs/nexus.log")
        _write_env(env)
        st.success("Credentials saved to .env")
        if naukri_email:
            st.info("Run `python orchestrator.py store-creds naukri` to also store in the OS keyring.")


def page_advanced() -> None:
    st.title("Advanced Settings")
    cfg      = _read_yaml(AGENT_CONFIG)
    apply_cfg = cfg.get("apply", {})
    llm_cfg  = cfg.get("llm", {})
    scout_cfg = cfg.get("scout", {})
    sched_cfg = cfg.get("schedule", {})

    with st.form("advanced_form"):
        st.subheader("Apply Behaviour")
        c1, c2 = st.columns(2)
        with c1:
            live_mode = st.toggle("Live Mode — submits real applications",
                                  value=apply_cfg.get("live_mode", False),
                                  help="Keep OFF until tested with --dry-run")
            headless  = st.checkbox("Headless Browser", value=apply_cfg.get("headless", True))
        with c2:
            retry   = st.number_input("Retry Attempts",      0, 10,   int(apply_cfg.get("retry_attempts",2)))
            slow_mo = st.number_input("Browser Slow-Mo (ms)",0, 2000, int(apply_cfg.get("slow_mo_ms",50)), step=10)
        captcha_opts = ["skip_and_flag","pause_for_human","abort"]
        captcha = st.selectbox("On CAPTCHA", captcha_opts,
                               index=captcha_opts.index(apply_cfg.get("on_captcha","skip_and_flag")))

        st.subheader("Ollama LLM (Scorer)")
        c1, c2, c3 = st.columns(3)
        with c1: ollama_url    = st.text_input("Base URL", value=llm_cfg.get("base_url","http://localhost:11434"))
        with c2: scorer_model  = st.text_input("Model",    value=llm_cfg.get("scorer_model","llama3.2"))
        with c3: temperature   = st.slider("Temperature", 0.0, 1.0, float(llm_cfg.get("temperature",0.3)), step=0.05)

        st.subheader("Scout")
        c1, c2 = st.columns(2)
        with c1: max_jobs = st.number_input("Max Jobs per Run",       10, 500, int(scout_cfg.get("max_jobs_per_run",100)))
        with c2: interval = st.number_input("Scout Interval (minutes)", 5, 120, int(sched_cfg.get("scout_interval_minutes",30)))

        submitted = st.form_submit_button("Save Advanced Settings", type="primary")

    if submitted:
        if live_mode and not apply_cfg.get("live_mode", False):
            st.warning("Live mode is now ON — Nexus will submit real applications on the next run.")
        cfg.setdefault("apply", {}).update({
            "live_mode": live_mode, "headless": headless,
            "retry_attempts": int(retry), "slow_mo_ms": int(slow_mo), "on_captcha": captcha,
        })
        cfg.setdefault("llm", {}).update({
            "base_url": ollama_url, "scorer_model": scorer_model, "temperature": float(temperature),
        })
        cfg.setdefault("scout", {})["max_jobs_per_run"] = int(max_jobs)
        cfg.setdefault("schedule", {})["scout_interval_minutes"] = int(interval)
        _write_yaml(AGENT_CONFIG, cfg, "# ─── Nexus Agent Configuration ──────────────────────────────────────────────")
        st.success("Advanced settings saved.")


# ── App shell ──────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Nexus",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)

PAGES = {
    "🏠  Dashboard":                page_dashboard,
    "⚙️  Settings":                 page_settings_wizard,
    "🔔  Notifications & Credentials": page_notifications,
    "🔧  Advanced":                 page_advanced,
}

with st.sidebar:
    st.markdown("## 🎯 Nexus")
    st.caption("Autonomous Job Hunt Agent")
    st.divider()
    page = st.radio("", list(PAGES.keys()), label_visibility="collapsed")
    st.divider()
    live = _read_yaml(AGENT_CONFIG).get("apply", {}).get("live_mode", False)
    if live:
        st.error("Live mode ON")
    else:
        st.success("Safe mode (dry-run)")

PAGES[page]()